import React, { useState } from 'react';
import { DisclaimerBanner } from '../components/DisclaimerBanner';
import {
  BookOpen,
  Heart,
  Droplet,
  Scan,
  Activity,
  Layers,
  Search,
  ChevronDown,
  ChevronUp,
  AlertCircle,
  ShieldCheck,
  Stethoscope
} from 'lucide-react';

const MEDICAL_GUIDES = [
  {
    id: 'ecg',
    name: 'ECG (Electrocardiogram)',
    category: 'Cardiology',
    icon: Heart,
    summary: 'A non-invasive diagnostic test that records the electrical activity and rhythm of your heart.',
    whatIsIt: 'An ECG records electrical impulses generated by heart muscle contractions using adhesive sensor pads placed on the chest, arms, and legs.',
    whyIsItDone: 'To investigate palpitations, chest tightness, shortness of breath, unexplained fainting, or monitor known arrhythmias and medication effects.',
    doctor: 'Cardiologist, General Physician, Emergency Medicine Consultant',
    preparation: 'Avoid heavy caffeinated beverages before testing. Wear comfortable two-piece clothing for easy sensor placement. Men may have small chest areas clipped if necessary.',
    referenceValues: 'Normal resting heart rate is typically 60-100 beats per minute with regular sinus rhythm.'
  },
  {
    id: 'blood-cbc',
    name: 'Complete Blood Count (CBC) & Lipid Profile',
    category: 'Laboratory',
    icon: Droplet,
    summary: 'Essential blood test evaluating overall cellular health, oxygen capacity, infection markers, and cholesterol levels.',
    whatIsIt: 'A laboratory analysis of venous blood measuring Red Blood Cells (Hemoglobin/RBC), White Blood Cells (WBC), Platelets, and serum lipids (Cholesterol, HDL, LDL, Triglycerides).',
    whyIsItDone: 'To detect anemia, hidden bacterial or viral infections, bleeding tendencies, cardiovascular risk factors, or monitor overall metabolic vitality.',
    doctor: 'Pathologist, General Physician, Hematologist, Cardiologist',
    preparation: 'For lipid panels and fasting blood sugar, 10 to 12 hours of overnight water-only fasting is standard. Routine CBC without lipids does not always require fasting.',
    referenceValues: 'Hemoglobin: 13.0-17.0 g/dL (men), 12.0-15.5 g/dL (women). Total Cholesterol: ideally under 200 mg/dL.'
  },
  {
    id: 'xray',
    name: 'X-Ray (Radiography)',
    category: 'Radiology',
    icon: Scan,
    summary: 'Fast, painless diagnostic imaging that produces shadows of bones, joints, and dense tissues like lungs.',
    whatIsIt: 'Low-dose electromagnetic radiation passes through the body and is absorbed differently depending on tissue density (dense bones appear white, air in lungs appears dark).',
    whyIsItDone: 'To identify bone fractures, joint dislocations, chest infections (such as pneumonia), fluid in lungs, or arthritis.',
    doctor: 'Radiologist, Orthopedic Surgeon, Pulmonologist',
    preparation: 'Remove all metal jewelry, eyeglasses, piercings, and belt buckles from the imaging region. Inform the technician if you are pregnant.',
    referenceValues: 'Intact bony cortices without cortical breaks; lung fields clear without consolidations or effusions.'
  },
  {
    id: 'mri',
    name: 'MRI (Magnetic Resonance Imaging)',
    category: 'Radiology',
    icon: Layers,
    summary: 'Detailed imaging utilizing strong magnetic fields and radio waves to capture soft tissues, brain, and spine.',
    whatIsIt: 'Unlike X-rays, MRI uses powerful magnets and computer algorithms to generate multi-angle, 3D cross-sectional slices of soft organs, ligaments, cartilage, and nerves.',
    whyIsItDone: 'To evaluate brain tissue, spinal discs, torn knee ligaments (ACL/meniscus), abdominal organs, or deep soft-tissue tumors.',
    doctor: 'Radiologist, Neurologist, Orthopedic Surgeon, Neurosurgeon',
    preparation: 'Strictly remove all metallic items. You must inform the technician if you have a cardiac pacemaker, cochlear implants, or metallic surgical clips.',
    referenceValues: 'Normal anatomical alignment without nerve root impingement, disc herniation, or focal soft-tissue lesions.'
  },
  {
    id: 'ct-scan',
    name: 'CT Scan (Computed Tomography)',
    category: 'Radiology',
    icon: Scan,
    summary: 'Rotational 360-degree X-ray technology that creates high-resolution cross-sectional slices of internal organs.',
    whatIsIt: 'A motorized X-ray tube rotates around the patient inside a donut-shaped gantry, producing slice-by-slice computerized cross sections of internal anatomy.',
    whyIsItDone: 'To detect internal bleeding, trauma injuries, acute abdominal pain (appendicitis), pulmonary embolisms, or tumor staging.',
    doctor: 'Radiologist, General Surgeon, Emergency Medicine, Oncologist',
    preparation: 'If intravenous contrast dye is required, 4 hours of prior fasting and a recent kidney function test (serum creatinine) are typically required.',
    referenceValues: 'Homogeneous parenchymal density without focal lesions or internal organ lacerations.'
  },
  {
    id: 'ultrasound',
    name: 'Ultrasound / Sonography (USG)',
    category: 'Radiology',
    icon: Activity,
    summary: 'Completely radiation-free imaging utilizing high-frequency sound waves to view organs and blood flow.',
    whatIsIt: 'A handheld transducer probe transmits sound waves into the body and interprets returning acoustic echoes to visualize internal structures in real-time.',
    whyIsItDone: 'To examine the liver, kidneys, gallbladder (gallstones), pelvic organs, fetal development during pregnancy, or vascular Doppler flow.',
    doctor: 'Radiologist, Obstetrician/Gynecologist, Gastroenterologist',
    preparation: 'For abdominal scans, 6 hours fasting is usually required to minimize bowel gas. For pelvic and urinary scans, drinking water to maintain a full bladder is essential.',
    referenceValues: 'Normal organ dimensions and acoustic echotexture without acoustic shadowing stones or cystic masses.'
  },
  {
    id: 'bp-report',
    name: 'Blood Pressure Assessment & Ambulatory Log',
    category: 'General Medicine',
    icon: Stethoscope,
    summary: 'Measurement of the pressure exerted by circulating blood against the walls of systemic arteries.',
    whatIsIt: 'Expressed as two numbers in millimeters of mercury (mmHg): Systolic (pressure during heart contraction) over Diastolic (pressure during resting filling).',
    whyIsItDone: 'To screen for hypertension (high BP), hypotension (low BP), cardiovascular risk, or verify effectiveness of antihypertensive medication.',
    doctor: 'Cardiologist, General Physician, Nephrologist',
    preparation: 'Rest quietly in a chair with feet flat on the floor for 5 minutes before measurement. Avoid nicotine, exercise, or caffeine 30 minutes prior.',
    referenceValues: 'Optimal: < 120/80 mmHg. Elevated: 120-129 / < 80 mmHg. Stage 1 Hypertension: 130-139 / 80-89 mmHg.'
  }
];

export const ReportGuidePage = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [expandedId, setExpandedId] = useState('ecg');

  const filteredGuides = MEDICAL_GUIDES.filter(guide => {
    const q = searchTerm.toLowerCase();
    return guide.name.toLowerCase().includes(q) ||
      guide.category.toLowerCase().includes(q) ||
      guide.summary.toLowerCase().includes(q) ||
      guide.doctor.toLowerCase().includes(q);
  });

  return (
    <div className="content-wrapper">
      <DisclaimerBanner compact />

      {/* Header */}
      <div className="page-header">
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
            <h1 className="page-title">Educational Medical Report Guide</h1>
            <span className="badge badge-success">Peer-Reviewed Educational Content</span>
          </div>
          <p className="page-subtitle">
            Understand what common diagnostic tests mean, why doctors order them, and general preparation tips in plain language.
          </p>
        </div>
      </div>

      {/* Educational Notice Banner */}
      <div style={{
        background: '#f0fdf4',
        border: '1px solid #bbf7d0',
        borderRadius: 'var(--radius-lg)',
        padding: '1rem 1.25rem',
        marginBottom: '1.75rem',
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        fontSize: '0.85rem',
        color: '#166534'
      }}>
        <ShieldCheck size={22} color="#16a34a" style={{ flexShrink: 0 }} />
        <div>
          <strong>Educational Reference Only:</strong> All explanations provided in this guide are synthesized from established medical diagnostic reference standards for patient health literacy. This material does <em>not</em> constitute a medical diagnosis or treatment plan. Always consult your qualified healthcare practitioner regarding your specific laboratory findings.
        </div>
      </div>

      {/* Search Input */}
      <div className="cs-card" style={{ padding: '1rem', marginBottom: '1.75rem' }}>
        <div style={{ position: 'relative' }}>
          <input
            type="text"
            className="form-control"
            placeholder="Search report guide by test name (e.g. ECG, CBC, Ultrasound, MRI, Blood Pressure)..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            style={{ paddingLeft: '2.5rem' }}
          />
          <Search size={18} color="var(--text-muted)" style={{ position: 'absolute', left: '0.85rem', top: '50%', transform: 'translateY(-50%)' }} />
        </div>
      </div>

      {/* Guide Accordion / Cards */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        {filteredGuides.map(guide => {
          const Icon = guide.icon;
          const isExpanded = expandedId === guide.id;

          return (
            <div
              key={guide.id}
              className="cs-card"
              style={{
                borderColor: isExpanded ? 'var(--primary)' : 'var(--border-light)',
                boxShadow: isExpanded ? 'var(--shadow-md)' : 'var(--shadow-sm)'
              }}
            >
              {/* Clickable Header */}
              <div
                onClick={() => setExpandedId(isExpanded ? null : guide.id)}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  cursor: 'pointer',
                  userSelect: 'none'
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.85rem' }}>
                  <div style={{
                    width: '42px',
                    height: '42px',
                    borderRadius: '12px',
                    background: isExpanded ? 'var(--primary-light)' : '#f8fafc',
                    color: isExpanded ? 'var(--primary)' : '#64748b',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0
                  }}>
                    <Icon size={22} />
                  </div>
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <h3 style={{ fontSize: '1.15rem', fontWeight: 800, color: '#0f172a' }}>
                        {guide.name}
                      </h3>
                      <span className="badge badge-other" style={{ fontSize: '0.725rem' }}>
                        {guide.category}
                      </span>
                    </div>
                    <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginTop: '0.15rem' }}>
                      {guide.summary}
                    </p>
                  </div>
                </div>

                <div style={{ color: 'var(--primary)', padding: '0.25rem' }}>
                  {isExpanded ? <ChevronUp size={22} /> : <ChevronDown size={22} />}
                </div>
              </div>

              {/* Expanded Educational Body */}
              {isExpanded && (
                <div style={{
                  marginTop: '1.25rem',
                  paddingTop: '1.25rem',
                  borderTop: '1px solid var(--border-light)',
                  display: 'grid',
                  gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
                  gap: '1.25rem'
                }}>
                  {/* What is it */}
                  <div style={{ background: '#f8fafc', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid #f1f5f9' }}>
                    <h4 style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--primary)', marginBottom: '0.35rem' }}>
                      🔬 What is it?
                    </h4>
                    <p style={{ fontSize: '0.85rem', color: '#334155', lineHeight: 1.5 }}>
                      {guide.whatIsIt}
                    </p>
                  </div>

                  {/* Why is it done */}
                  <div style={{ background: '#f8fafc', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid #f1f5f9' }}>
                    <h4 style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--teal)', marginBottom: '0.35rem' }}>
                      🎯 Why is it ordered?
                    </h4>
                    <p style={{ fontSize: '0.85rem', color: '#334155', lineHeight: 1.5 }}>
                      {guide.whyIsItDone}
                    </p>
                  </div>

                  {/* Which doctor */}
                  <div style={{ background: '#f8fafc', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid #f1f5f9' }}>
                    <h4 style={{ fontSize: '0.9rem', fontWeight: 700, color: '#7e22ce', marginBottom: '0.35rem' }}>
                      👨‍⚕️ Which specialist commonly uses it?
                    </h4>
                    <p style={{ fontSize: '0.85rem', color: '#334155', lineHeight: 1.5 }}>
                      {guide.doctor}
                    </p>
                  </div>

                  {/* Preparation */}
                  <div style={{ background: '#f8fafc', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid #f1f5f9' }}>
                    <h4 style={{ fontSize: '0.9rem', fontWeight: 700, color: '#d97706', marginBottom: '0.35rem' }}>
                      📋 General Preparation Guidelines
                    </h4>
                    <p style={{ fontSize: '0.85rem', color: '#334155', lineHeight: 1.5 }}>
                      {guide.preparation}
                    </p>
                  </div>

                  {/* General Reference Benchmark */}
                  <div style={{ gridColumn: '1 / -1', background: '#f0fdfa', padding: '0.85rem 1rem', borderRadius: 'var(--radius-md)', border: '1px solid #ccfbf1' }}>
                    <span style={{ fontSize: '0.8rem', fontWeight: 700, color: '#0f766e' }}>General Reference Norm: </span>
                    <span style={{ fontSize: '0.825rem', color: '#134e4a' }}>{guide.referenceValues}</span>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
